version: '3.7'
services:
  flask:
    container_name: flask
    build: .
    ports:
      - 5000:5000
    volumes:
      - .:/app
    environment:
      - CPLUS_INCLUDE_PATH=/usr/include/gdal
      - C_INCLUDE_PATH=/usr/include/gdal